"""Production database gate, explicit first-party SSO trust, and signed synthetic payment boundary tests."""
from dataclasses import replace
from datetime import datetime, timezone

import httpx
import pytest
from sqlalchemy import select

from app.config import settings
from app.db_admin import migration_manifest
from app.models import OAuthClient, SchemaMigration, User
from app.security import hash_password
from app.startup_checks import ProductionConfigError, enforce_database_safety
from app.wechat_pay import WeChatPayError, assert_notify_identity, native_prepay
from tests.conftest import TestSession
from tests.test_download import auth_headers
from tests.test_wechat_notify import (
    CERT_PEM,
    PUBKEY_PEM,
    build_notify,
    fetch,
    make_order,
    post_notify,
    txn,
)
from tests.test_wechat_notify import notify_ready as notify_ready
from tests.test_wechat_pay import CFG, signed_response


@pytest.fixture
async def safe_database(client, monkeypatch):
    async with TestSession() as db:
        db.add_all([SchemaMigration(version=v, checksum=digest) for v, (_, digest) in migration_manifest().items()])
        db.add(User(username='owner', password=hash_password('synthetic-owner-password'), role=1))
        for c in (await db.scalars(select(OAuthClient))).all():
            c.status = 0  # HTTP fixtures contain explicit test clients; production cannot use their known secrets.
        await db.commit()
    monkeypatch.setattr(settings, 'ENV', 'production')


async def test_production_accepts_current_ledger_and_non_demo_owner(safe_database):
    await enforce_database_safety(TestSession)


async def test_production_requires_ledger(client, monkeypatch):
    monkeypatch.setattr(settings, 'ENV', 'production')
    with pytest.raises(ProductionConfigError):
        await enforce_database_safety(TestSession)


@pytest.mark.parametrize('kind', ['admin', 'client', 'missing_admin', 'checksum', 'pending', 'renamed_admin'])
async def test_production_rejects_demo_rehashed_secrets_and_bad_ledger(safe_database, kind):
    async with TestSession() as db:
        if kind in ('admin', 'renamed_admin'):
            db.add(User(username='admin' if kind == 'admin' else 'renamed', password=hash_password('123456'), role=1))
        elif kind == 'client':
            client = await db.scalar(select(OAuthClient).where(OAuthClient.client_id == 'tools'))
            client.status = 1  # hash was freshly generated by fixture, not the static seed hash
        elif kind == 'missing_admin':
            owner = await db.scalar(select(User).where(User.username == 'owner'))
            owner.role = 0
        elif kind == 'pending':
            await db.delete(await db.get(SchemaMigration, '0009'))
        else:
            (await db.get(SchemaMigration, '0001')).checksum = 'bad'
        await db.commit()
    with pytest.raises(ProductionConfigError):
        await enforce_database_safety(TestSession)


async def test_production_oauth_requires_explicit_first_party_allowlist(client, monkeypatch):
    headers = await auth_headers(client)
    monkeypatch.setattr(settings, 'ENV', 'production')
    monkeypatch.setattr(settings, 'OAUTH_TRUSTED_CLIENT_IDS', ())
    params = {'client_id': 'tools', 'redirect_uri': 'https://tools.codemax.top/callback', 'response_type': 'code'}
    assert (await client.get('/oauth/authorize', params=params, headers=headers)).status_code == 400
    data = {'grant_type': 'authorization_code', 'client_id': 'tools', 'client_secret': 'codemax-tools-secret',
            'code': 'absent', 'redirect_uri': params['redirect_uri']}
    assert (await client.post('/oauth/token', data=data)).json()['detail']['error'] == 'invalid_client'
    monkeypatch.setattr(settings, 'OAUTH_TRUSTED_CLIENT_IDS', ('tools',))
    assert (await client.get('/oauth/authorize', params=params, headers=headers)).status_code == 200


@pytest.mark.parametrize('field,value', [('appid', 'foreign'), ('mchid', 'foreign'), ('trade_type', 'JSAPI'), ('currency', 'USD')])
async def test_signed_payment_must_match_business_identity(client, notify_ready, field, value):
    number = await make_order()
    data = txn(number)
    (data['amount'] if field == 'currency' else data)[field] = value
    response = await post_notify(client, *build_notify(data))
    assert response.status_code == 400 and (await fetch(number)).status == 'pending'


async def test_valid_signature_with_wrong_platform_serial_is_rejected(client, notify_ready):
    number = await make_order()
    body, headers = build_notify(txn(number))
    headers['Wechatpay-Serial'] = 'UNKNOWN'
    assert (await post_notify(client, body, headers)).status_code == 401
    assert (await fetch(number)).status == 'pending'


def test_certificate_validity_and_raw_public_key_id():
    from cryptography import x509
    cert_cfg = replace(CFG, platform_cert=CERT_PEM)
    serial = format(x509.load_pem_x509_certificate(CERT_PEM.encode()).serial_number, 'X')
    assert_notify_identity(cert_cfg, serial)
    for year in (2010, 2050):
        with pytest.raises(WeChatPayError):
            assert_notify_identity(cert_cfg, serial, now=datetime(year, 1, 1, tzinfo=timezone.utc))
    cfg = replace(CFG, platform_cert=PUBKEY_PEM, platform_key_id='PUB_KEY_ID_TEST')
    assert cfg.notify_ready
    assert_notify_identity(cfg, 'PUB_KEY_ID_TEST')
    with pytest.raises(WeChatPayError):
        assert_notify_identity(cfg, 'PUB_KEY_ID_OTHER')
    assert not replace(cfg, platform_key_id='').notify_ready


@pytest.mark.parametrize('body', [b'[]', b'null', b'\xff', b'x'*65537, b'{"code_url":true}', b'{"code_url":"https://foreign.invalid"}'])
async def test_malformed_prepay_response_fails_without_body_leak(body):
    transport = httpx.MockTransport(lambda request: signed_response(body))
    with pytest.raises(WeChatPayError) as error:
        await native_prepay(CFG, out_trade_no='test', description='test', total=1, transport=transport)
    assert len(str(error.value)) < 150 and 'foreign.invalid' not in str(error.value)


async def test_prepay_network_error_is_controlled_and_redacted():
    def fail(request):
        raise httpx.ConnectError('private diagnostics and credentials must not escape')
    with pytest.raises(WeChatPayError) as error:
        await native_prepay(CFG, out_trade_no='test', description='test', total=1, transport=httpx.MockTransport(fail))
    assert 'private' not in str(error.value)


async def test_prepay_has_total_deadline_not_only_per_read_timeout(monkeypatch):
    import asyncio

    import app.wechat_pay as payments

    monkeypatch.setattr(payments, 'TIMEOUT', 0.01)
    async def slow(request):
        await asyncio.sleep(1)
        return httpx.Response(200, json={'code_url': 'weixin://slow'})
    with pytest.raises(WeChatPayError):
        await native_prepay(CFG, out_trade_no='test', description='test', total=1, transport=httpx.MockTransport(slow))


def test_decrypted_invalid_utf8_is_a_controlled_payment_error():
    import base64

    from cryptography.hazmat.primitives.ciphers.aead import AESGCM

    from app.wechat_pay import decrypt_resource
    from tests.test_wechat_notify import AES_NONCE, API_V3_KEY

    raw = AESGCM(API_V3_KEY.encode()).encrypt(AES_NONCE.encode(), b'\xff', b'')
    with pytest.raises(WeChatPayError):
        decrypt_resource(API_V3_KEY, nonce=AES_NONCE, ciphertext=base64.b64encode(raw).decode())


async def test_oauth_nul_code_is_not_a_database_error(client):
    response = await client.post('/oauth/token', data={
        'grant_type': 'authorization_code', 'client_id': 'tools', 'client_secret': 'codemax-tools-secret',
        'code': 'bad\x00code', 'redirect_uri': 'https://tools.codemax.top/callback',
    })
    assert response.status_code == 400 and response.json()['detail']['error'] == 'invalid_grant'


def test_container_context_and_compose_keep_explicit_initialization():
    from pathlib import Path
    root = Path(__file__).resolve().parents[1]
    ignored = (root / '.dockerignore').read_text(encoding='utf-8').splitlines()
    assert 'database init' not in ignored and 'database init/' not in ignored and '*.sql' not in ignored
    compose = (root / 'docker-compose.yml').read_text(encoding='utf-8')
    assert '/docker-entrypoint-initdb.d/' not in compose
    assert 'DATABASE_URL: ""' in compose


@pytest.mark.parametrize('cfg', [
    replace(CFG, platform_cert=''),
    replace(CFG, platform_cert='-----BEGIN CERTIFICATE-----invalid'),
    replace(CFG, api_v3_key='short'),
])
async def test_prepay_refuses_unusable_callback_configuration(client, monkeypatch, cfg):
    from app.models import Order
    from app.routers import shop

    headers = await auth_headers(client)
    monkeypatch.setattr(settings, 'SHOP_PAY_MODE', 'wechat')
    monkeypatch.setattr(shop, 'pay_config', lambda: cfg)
    async def never_call(*args, **kwargs):
        pytest.fail('must not charge when callback credentials cannot be used')
    monkeypatch.setattr(shop, 'native_prepay', never_call)
    assert (await client.post('/shop/orders', headers=headers)).status_code == 503
    async with TestSession() as db:
        assert (await db.scalars(select(Order))).all() == []
